for-mom2/config/routes.rb
ForMom2::Application.routes.draw do
  get "welcome/index"
  get "schools/index"
  get "users/index"
  
  root 'welcome#index'

  resources :users 
  resources :schools do
    resources :prompts
  end
  resources :responses

  

end

for-mom2/app/models/applying.rb
class Applying < ActiveRecord::Base
  belongs_to :school
  belongs_to :user
end

for-mom2/app/models/prompt.rb
class Prompt < ActiveRecord::Base
  belongs_to :school
  has_many :responses

end

for-mom2/app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :prompt

end

for-mom2/app/models/school.rb
class School < ActiveRecord::Base
  has_many :applyings
  has_many :users, through: :applyings

  has_many :prompts
end

for-mom2/app/models/user.rb
class User < ActiveRecord::Base
  has_many :applyings
  has_many :schools, through: :applyings

  def school_list
    self.schools.collect do |school|
      school.name
    end.join(", ")
  end

  def school_list=(schools_string)
    school_names = schools_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_schools = school_names.collect { |name| School.find_or_create_by(name: name) }
    self.schools = new_or_found_schools
  end

end

for-mom2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

for-mom2/app/controllers/prompts_controller.rb
class PromptsController < ApplicationController
  def create
    @school = School.find(params[:school_id])
    @prompt = @school.prompts.create(prompt_params)

    redirect_to school_path(@school)
  end

  def show
    @school = School.find(params[:school_id])
    @school_id = @school.id

    @prompt = @school.prompts.find(params[:id])
    @prompt_id = @prompt.id
  end

private
  def prompt_params
    params.required(:prompt).permit(:question, :id, :school_id)
  end
end

for-mom2/app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  def new
    @response = Response.new
  end

  def create
    @response = Response.new(response_params)
    @response.save

    redirect_to school_prompt_path(school_id: @response.school_id, id: @response.prompt)
  end

  def show
    @response = Response.find(params[:id])
  end

  def destroy
    @response = Response.find(params[:id])
    @response.destroy

    redirect_to responses_path
  end

private
  def response_params
    params.required(:response).permit(:submitter, :comments, :prompt_id, :school_id)
  end
end

for-mom2/app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def index
    @schools = School.all
  end

  def new
    @school = School.new
  end

  def create
    @school = School.new(school_params)
    @school.save
    
    redirect_to school_path(@school)
  end

  def show
    @school = School.find(params[:id])
  end

  def destroy
    @school = School.find(params[:id])
    @school.destroy

    redirect_to schools_path
  end  

private
  def school_params
    params.required(:school).permit(:name, :id)
  end
end

for-mom2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    
    redirect_to user_path(@user)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    
    redirect_to user_path(@user)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    
    redirect_to users_path
  end

private
  def user_params
    params.required(:user).permit(:name, :grad_year, :high_school, :school_list)
  end
end

for-mom2/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

for-mom2/app/helpers/application_helper.rb
module ApplicationHelper
end

for-mom2/app/helpers/prompts_helper.rb
module PromptsHelper
end

for-mom2/app/helpers/responses_helper.rb
module ResponsesHelper
end

for-mom2/app/helpers/schools_helper.rb
module SchoolsHelper
end

for-mom2/app/helpers/users_helper.rb
module UsersHelper
end

for-mom2/app/helpers/welcome_helper.rb
module WelcomeHelper
end

for-mom2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ForMom2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

for-mom2/app/views/prompts/show.html.erb
<h1><%= @prompt.question %></h1>

<h2>View responses</h2>
<% if @prompt.responses.length == 0 %>
  <p><i>There hasn't yet been a response to this question</i></p>
<% else %>
  <% @prompt.responses.each do |response| %>
    <p><strong><%= response.submitter %></strong></p>
    <p><%= response.comments %></p>
    <p><%= response.created_at %></p>
  <% end %>
<% end %>

<h2>Add a response</h2>
<%= form_for(Response.new) do |f| %>
  <p>
    <%= f.label :submitter %><br />
    <%= f.text_field :submitter %>
  </p>
  <p>
    <%= f.label :comments %><br />
    <%= f.text_field :comments %>
  </p>
  <p>
    <%= f.label :school_id %><br />
    <%= f.text_field :school_id, :value => @school_id %>
  </p>
  <p>
    <%= f.label :prompt_id %><br />
    <%= f.text_field :prompt_id, :value => @prompt_id %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to "View info for #{@prompt.school.name}", school_path(@prompt.school.id) %>

for-mom2/app/views/schools/index.html.erb
<h1>All schools</h1>

  <table style="width:450px">
    <tr>
      <th>University Name</th>
      <th># of students</th>
    </tr>

    <% School.all.each do |school| %>
      <tr>
        <td><%= link_to school.name, school_path(school) %></td>
        <td><%= school.users.length %></td>
      </tr>
    <% end %>
  </table>

<br/>
<%= link_to "Add a New School", new_school_path %> <br/><br/>
<%= link_to "See all students", users_path %>

for-mom2/app/views/schools/new.html.erb
<%= form_for(@school, html: {multipart:true}) do |f| %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to "See all schools", schools_path, data: {confirm: "Are you sure you want to go back?"} %>

for-mom2/app/views/schools/show.html.erb
<h1><%= @school.name %></h1>

<h2>Students applying here:</h2>
<% if @school.users.length > 0 %>
  <ul>
    <% @school.users.each do |user| %>
      <li><%= link_to user.name, user_path(user) %></li>
    <% end %>
  </ul>
<% else %>
  <p><i>No one has yet chosen to apply here</i></p>
  <p><%= link_to "See all students", users_path %></p>
<% end %>

<h2>Essay prompts</h2>
<% if @school.prompts.length == 0 %>
  <p><i>You haven't added any prompts for this school</i></p>
<% end %>

<% @school.prompts.each do |prompt| %>
  <p>
     <%= prompt.question %>
     <%= link_to 'Responses >>', school_prompt_path(school_id: @school, id: prompt.id) %>
  </p>
  </br>
<% end %>

<%= form_for([@school, @school.prompts.build]) do |f| %>
  <p>
    <%= f.label 'Add a prompt:' %><br />
    <%= f.text_area :question %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

for-mom2/app/views/users/_form.html.erb
<%= form_for(@user, html: {multipart:true}) do |f| %>
  <ul>
  <% @user.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :grad_year %><br />
    <%= f.text_field :grad_year %>
  </p>
  <p>
    <%= f.label :high_school %><br />
    <%= f.text_field :high_school %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

for-mom2/app/views/users/index.html.erb
<h1>All users</h1>

  <table style="width:450px">
    <tr>
      <th>Student Name</th>
      <th>Info</th>
      <th># of schools</th>
    </tr>

    <% User.all.each do |user| %>
      <tr>
        <td><%= link_to user.name, user_path(user) %></td>
        <td><%= user.schools.length %></td>
        <td><%= user.high_school%>, <%= user.grad_year %></td>
      </tr>
    <% end %>
  </table>

</br>
<%= link_to "Create a New User", new_user_path %></br>
<%= link_to "See all schools", schools_path %>

for-mom2/app/views/users/new.html.erb
<h1>Create a New User</h1>

<%= render partial: 'form' %>

<%= link_to "See all users", users_path, data: {confirm: "Are you sure you want to go back? You'll lose your data."} %>

for-mom2/app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<h3><%= @user.high_school %>, class of <%= @user.grad_year %></h3>

<h2>Schools:</h2>
  <ul>
    <% @user.schools.each do |school| %>
      <li><%= link_to school.name, school_path(school) %></li>
    <% end %>
  </ul>

<h2> Add a school </h2>
<%= form_for(@user, html: {multipart:true}) do |f| %>
  <p>
    <%= f.label :school_list %><br />
    <%= f.text_field :school_list %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<br/>

<%= link_to "See all users", users_path %>

for-mom2/app/views/welcome/index.html.erb
<h1>Welcome to Randi's Get-Into-College Consulting!</h1>

<hr>

<h2>All users</h2>

  <table style="width:450px">
    <tr>
      <th>Student Name</th>
      <th>Info</th>
      <th># of schools</th>
    </tr>

    <% User.all.each do |user| %>
      <tr>
        <td><%= link_to user.name, user_path(user) %></td>
        <td><%= user.schools.length %></td>
        <td><%= user.high_school%>, <%= user.grad_year %></td>
      </tr>
    <% end %>
  </table>

  </br>
  <%= link_to "Create a New User", new_user_path %>

<hr>

<h2>All schools</h2>

  <table style="width:450px">
    <tr>
      <th>University Name</th>
      <th># of students</th>
    </tr>

    <% School.all.each do |school| %>
      <tr>
        <td><%= link_to school.name, school_path(school) %></td>
        <td><%= school.users.length %></td>
      </tr>
    <% end %>
  </table>

  </br>
  <%= link_to "Add a new school", new_school_path %>